name       : rclone
version    : 1.57.0
release    : 22
source     :
    - https://github.com/rclone/rclone/releases/download/v1.57.0/rclone-v1.57.0.tar.gz : 3a762c02c202a9142c2d5c1a3927563a556d1683abadd25d2f695e237e4ea693
license    : MIT
component  : network.util
networking : yes
summary    : Sync files to and from Google Drive, S3, Swift, Cloudfiles, etc.
description: |
    Sync files to and from Google Drive, S3, Swift, Cloudfiles, Dropbox and Google Cloud Storage
builddeps  :
    - golang
setup      : |
    %patch -p1 < $pkgfiles/01-fix-version-from-archive-sources.patch
build      : |
    %make
    ./rclone genautocomplete bash rclone.bash_completion
    ./rclone genautocomplete fish rclone.fish_completion
    ./rclone genautocomplete zsh rclone.zsh_completion
install    : |
    install -Dm 00755 rclone -t $installdir/usr/bin
    install -Dm 00644 rclone.1 -t $installdir/usr/share/man/man1
    install -Dm 00644 MANUAL.* -t $installdir/usr/share/doc/rclone
    install -Dm 00644 rclone.bash_completion $installdir/usr/share/bash-completion/completions/rclone
    install -Dm 00644 rclone.fish_completion $installdir/usr/share/fish/vendor_completions.d/rclone.fish
    install -Dm 00644 rclone.zsh_completion $installdir/usr/share/zsh/site-functions/_rclone
