name       : rclone
version    : 1.56.2
release    : 21
source     :
    - https://github.com/rclone/rclone/releases/download/v1.56.2/rclone-v1.56.2.tar.gz : a8813d25c4640e52495fee83e525e76283c63f01d1cce8fbb58d8486b0c20c8a
license    : MIT
component  : network.util
networking : yes
summary    : Sync files to and from Google Drive, S3, Swift, Cloudfiles, etc.
description: |
    Sync files to and from Google Drive, S3, Swift, Cloudfiles, Dropbox and Google Cloud Storage
builddeps  :
    - golang
setup      : |
    %patch -p1 < $pkgfiles/01-fix-version-from-archive-sources.patch
build      : |
    %make
    ./rclone genautocomplete bash rclone.bash_completion
    ./rclone genautocomplete zsh rclone.zsh_completion
install    : |
    install -Dm 00755 rclone -t $installdir/usr/bin
    install -Dm 00644 rclone.1 -t $installdir/usr/share/man/man1
    install -Dm 00644 MANUAL.* -t $installdir/usr/share/doc/rclone
    install -Dm 00644 rclone.bash_completion $installdir/usr/share/bash-completion/completions/rclone
    install -Dm 00644 rclone.zsh_completion $installdir/usr/share/zsh/site-functions/_rclone
