name       : rclone
version    : 1.38
release    : 6
source     :
    - https://github.com/ncw/rclone/archive/v1.38.tar.gz : d4806a55b64ab54923b55b230f2b2679406d5de995884433d3d60516bb8ebcc0
license    : MIT
component  : network.util
networking : yes
summary    : Sync files to and from Google Drive, S3, Swift, Cloudfiles, etc.
description: |
    Sync files to and from Google Drive, S3, Swift, Cloudfiles, Dropbox and Google Cloud Storage
builddeps  :
    - golang
    - git
setup      : |
    # Set GOPATH
    export GOPATH="$workdir"

    # Downloading Dependencies
    go get github.com/ncw/rclone
build      : |
    # Building rclone
    export GOPATH="$workdir"
    go build -o "rclone"
install    : |
    # Install rclone an Man-Pages
    install -Dm 00755 rclone $installdir/usr/bin/rclone
    install -Dm 00644 rclone.1 $installdir/usr/share/man/man1/rclone.1
    install -dm 00755 $installdir/usr/share/doc/rclone
    install -m  00644 MANUAL.* -t $installdir/usr/share/doc/rclone
