name       : rclone
version    : 1.34
release    : 2
source     :
    - https://github.com/ncw/rclone/archive/v1.34.tar.gz : 8426b19e0a94149fcfc0d5d1fb481af4d907459165c46cdc2d6e8eeba22851a6
license    : MIT
component  : network.util
networking : yes
summary    : Sync files to and from Google Drive, S3, Swift, Cloudfiles, etc.
description: |
    Sync files to and from Google Drive, S3, Swift, Cloudfiles, Dropbox and Google Cloud Storage
builddeps  :
    - golang
    - git
setup      : |
    # Set GOPATH
    export GOPATH="$workdir"

    # Downloading Dependencies
    go get github.com/ncw/rclone
build      : |
    # Building rclone
    export GOPATH="$workdir"
    go build -o "rclone"
install    : |
    # Install rclone an Man-Pages
    install -D -m 00755 rclone $installdir/usr/bin/rclone
    install -D -m 00644 rclone.1 $installdir/usr/share/man/man1/rclone.1
