name       : rclone
version    : '1.35'
release    : 3
source     :
    - https://github.com/ncw/rclone/archive/v1.35.tar.gz : 63a075c4e6725f1a59c151a2d0d8cdf3119940fe293ee6220ff9fea6438b6fd7
license    : MIT
component  : network.util
networking : yes
summary    : Sync files to and from Google Drive, S3, Swift, Cloudfiles, etc.
description: |
    Sync files to and from Google Drive, S3, Swift, Cloudfiles, Dropbox and Google Cloud Storage
builddeps  :
    - golang
    - git
networking : yes
setup      : |
    # Set GOPATH
    export GOPATH="$workdir"

    # Downloading Dependencies
    go get github.com/ncw/rclone
build      : |
    # Building rclone
    export GOPATH="$workdir"
    go build -o "rclone"
install    : |
    # Install rclone an Man-Pages
    install -D -m 00755 rclone $installdir/usr/bin/rclone
    install -D -m 00644 rclone.1 $installdir/usr/share/man/man1/rclone.1
