name       : rclone
version    : 1.51.0
release    : 16
source     :
    - git|https://github.com/ncw/rclone : v1.51.0
license    : MIT
component  : network.util
networking : yes
summary    : Sync files to and from Google Drive, S3, Swift, Cloudfiles, etc.
description: |
    Sync files to and from Google Drive, S3, Swift, Cloudfiles, Dropbox and Google Cloud Storage
builddeps  :
    - golang
build      : |
    %make
    ./rclone genautocomplete bash rclone.bash_completion
    ./rclone genautocomplete zsh rclone.zsh_completion
install    : |
    install -Dm 00755 rclone -t $installdir/usr/bin
    install -Dm 00644 rclone.1 -t $installdir/usr/share/man/man1
    install -Dm 00644 MANUAL.* -t $installdir/usr/share/doc/rclone
    install -Dm 00644 rclone.bash_completion $installdir/usr/share/bash-completion/completions/rclone
    install -Dm 00644 rclone.zsh_completion $installdir/usr/share/zsh/site-functions/_rclone
