name       : rclone
version    : 1.41
release    : 9
source     :
    - https://github.com/ncw/rclone/archive/v1.41.tar.gz : 4f4cadb4db3a7daff7fa6539eb45273fad5203a0cc9c3a2bd8c2bdb8b349d872
license    : MIT
component  : network.util
networking : yes
summary    : Sync files to and from Google Drive, S3, Swift, Cloudfiles, etc.
description: |
    Sync files to and from Google Drive, S3, Swift, Cloudfiles, Dropbox and Google Cloud Storage
builddeps  :
    - golang
    - git
setup      : |
    mkdir -p .build/src/github.com/ncw
    ln -s $PWD .build/src/github.com/ncw/rclone
    export GOPATH=$PWD/.build

    go get github.com/ncw/rclone
build      : |
    export GOPATH=$PWD/.build
    go build -o rclone
install    : |
    install -Dm 00755 rclone -t $installdir/usr/bin
    install -Dm 00644 rclone.1 -t $installdir/usr/share/man/man1
    install -Dm 00644 MANUAL.* -t $installdir/usr/share/doc/rclone
