name       : rclone
version    : 1.37
release    : 5
source     :
    - https://github.com/ncw/rclone/archive/v1.37.tar.gz : a74e284d2368f6fb8e4ac654a31b9b1328ac6078acd3446c9a892cd4bcbe8660
license    : MIT
component  : network.util
networking : yes
summary    : Sync files to and from Google Drive, S3, Swift, Cloudfiles, etc.
description: |
    Sync files to and from Google Drive, S3, Swift, Cloudfiles, Dropbox and Google Cloud Storage
builddeps  :
    - golang
    - git
setup      : |
    # Set GOPATH
    export GOPATH="$workdir"

    # Downloading Dependencies
    go get github.com/ncw/rclone
build      : |
    # Building rclone
    export GOPATH="$workdir"
    go build -o "rclone"
install    : |
    # Install rclone an Man-Pages
    install -D -m 00755 rclone $installdir/usr/bin/rclone
    install -D -m 00644 rclone.1 $installdir/usr/share/man/man1/rclone.1
