name       : rclone
version    : '1.36'
release    : 4
source     :
    - https://github.com/ncw/rclone/archive/v1.36.tar.gz : a573b70e3aeb355b943dddd6ae9375386fc21bf12dfba601d8d7280f97c4c884
license    : MIT
component  : network.util
networking : yes
summary    : Sync files to and from Google Drive, S3, Swift, Cloudfiles, etc.
description: |
    Sync files to and from Google Drive, S3, Swift, Cloudfiles, Dropbox and Google Cloud Storage
builddeps  :
    - golang
    - git
setup      : |
    # Set GOPATH
    export GOPATH="$workdir"

    # Downloading Dependencies
    go get github.com/ncw/rclone
build      : |
    # Building rclone
    export GOPATH="$workdir"
    go build -o "rclone"
install    : |
    # Install rclone an Man-Pages
    install -D -m 00755 rclone $installdir/usr/bin/rclone
    install -D -m 00644 rclone.1 $installdir/usr/share/man/man1/rclone.1
